package rp3.data.models;

import java.util.ArrayList;

import android.database.Cursor;

import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

public class IdentificationType extends rp3.data.entity.EntityBase<IdentificationType> {

	private long id;
	private String name;
	private boolean applyNaturalPersonOnly;
	
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isApplyNaturalPersonOnly() {
		return applyNaturalPersonOnly;
	}

	public void setApplyNaturalPersonOnly(boolean applyNaturalPersonOnly) {
		this.applyNaturalPersonOnly = applyNaturalPersonOnly;
	}

	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return false;
	}

	@Override
	public String getTableName() {		
		return Contract.IdentificationType.TABLE_NAME;
	}

	@Override
	public void setValues() {
		setValue(Contract.IdentificationType._ID, id);
		setValue(Contract.IdentificationType.COLUMN_NAME, this.name);
		setValue(Contract.IdentificationType.COLUMN_APPLY_NATURAL_PERSON_ONLY, this.applyNaturalPersonOnly);
	}

	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return this.name;
	}
	
	public static ArrayList<IdentificationType> getAll(DataBase db)
	{
		Cursor c = db.query(Contract.IdentificationType.TABLE_NAME, new String[]{Contract.IdentificationType._ID, Contract.IdentificationType.COLUMN_NAME,
												Contract.IdentificationType.COLUMN_APPLY_NATURAL_PERSON_ONLY });
		ArrayList<IdentificationType> list = new ArrayList<IdentificationType>();
		if(c.moveToFirst())
		{
			do
			{
				IdentificationType setter = new IdentificationType();
				setter.id = CursorUtils.getLong(c,Contract.IdentificationType._ID);
				setter.name = CursorUtils.getString(c,Contract.IdentificationType.COLUMN_NAME);
				setter.applyNaturalPersonOnly = CursorUtils.getBoolean(c,Contract.IdentificationType.COLUMN_APPLY_NATURAL_PERSON_ONLY);
				list.add(setter);
			}while(c.moveToNext());
		}
		return list;
	}

	
	
}
